module logisimTopLevelShell(
    input  s_CLK,
    input  s_Cout,
    output s_A,
    output s_B,
    output s_C,
    output s_CLK_Out,
    output s_D,
    output s_E,
    output s_F,
    output s_G,
    output s_H,
    output s_QA,
    output s_QB,
    output s_QC,
    output s_QD,
    output s_QE,
    output s_QF,
    output s_QG,
    output s_QH,
    output s_SH,
    output s_ZERO
);

   main   CIRCUIT_0 (.A(s_A),
                     .B(s_B),
                     .C(s_C),
                     .CLK(s_CLK),
                     .CLK_Out(s_CLK_Out),
                     .Cout(s_Cout),
                     .D(s_D),
                     .E(s_E),
                     .F(s_F),
                     .G(s_G),
                     .H(s_H),
                     .QA(s_QA),
                     .QB(s_QB),
                     .QC(s_QC),
                     .QD(s_QD),
                     .QE(s_QE),
                     .QF(s_QF),
                     .QG(s_QG),
                     .QH(s_QH),
                     .SH(s_SH),
                     .ZERO(s_ZERO));
endmodule